### ISSUE TITLE
[ENHANCEMENT] subserver overarching mentions

### ISSUE THREAD

**Issue by johnzoki** [PantomInach/DataBot#117]
when somebody not in subserver gets mentioned in another subserver which he/she is part of, the bot could text the mentioned user about this event or subserver-channel could get visible to mentioned user.

**Comment by PantomInach** [comment]
For consistence, one would expect to receive a message when he is in the group of mentioned users. For a mention of `@everyone` all users not currently on the subserver should receive a message. This can lead to a great amount of messages the bot needs to send, which can take a while. Therefore, an option to disable the _indirect_ should also be included.

## Things to be implemented
1. Sending a mention message with a link to the channel should be sent to all mentioned users
2. Option for disabling the _indirect_ mention messages
3. Warning for the bot owner when the time to message every user exceeds a time span (e.g. 10 sec?)

**Comment by PantomInach** [comment]
Not planned to be implemented.
