### ISSUE TITLE
[ENHANCEMENT]  subserver overarching channel abos

### ISSUE THREAD

**Issue by johnzoki** [PantomInach/DataBot#118]
user could tag channels they want to get notified by even if they joined another subserver at that time.
somehow textchannels could disappear after reading unread messages so they aren't visible all the time?

**Comment by PantomInach** [comment]
No Discord Bot can get feedback on if a user read a message/clicked on a message channel of a server. Thus, it is not possible to make the text channel automatically disappear after a user read its messages.

Another possibility is to send the user one message per text channel if a new message is posted to this channel and the user is not in the channel's subserver. This could lead to a large amount of messages the bots need to send on an active server.

**Comment by PantomInach** [comment]
Not planned to be implemented.
